name: TeamUtils
version: '0.0.1.3'
main: com.karasu256.teamUtils.TeamUtils
api-version: '1.21'
authors: [ Hashibutogarasu ]
depend:
  - KarasuCommandAPI
  - KarasuConfigLib

commands:
  kteam:
    description: TeamUtils command
    usage: /kteam <subcommand>
    aliases: [ teamutils, tu ]
    permission: teamutils.command
    permission-message: You do not have permission to use this command.
    default: op